### ISSUE TITLE
Last few commits do not build

### ISSUE THREAD

**Issue by renedlog** [mrcsparker/nifi-sqllookup-services-bundle#2]
Hi, your last commits do all not build. See also:
https://travis-ci.org/mrcsparker/nifi-sqllookup-services-bundle

Using the 2 Month old "1.6.0-4" (the lastest one which can be build)

SQLRecordLookupService and SQLLookupService show up in the "LookupRecord" Processor, although one of them should be available in the "LookupAttribute" Processor

**Comment by phillipjohnson** [comment]
@renedlog I have a forked copy that builds here: https://github.com/phillipjohnson/nifi-sqllookup-services-bundle

**Comment by mrcsparker** [comment]
Merged your pull request.  Thanks
